

ktor {
    deployment {
        port = 8080,
        host = "0.0.0.0"
    }
    application {
        modules = [ com.example.luurk.ApplicationKt.module ]
    }
    database {
        url = "r2dbc:postgresql://localhost:5433/postgres"
        driver = "postgresql"
        user = "luurk-user"
        password = ${?DB_PASSWORD}
    }
    jwt {
        privateKey = ${JWT_PK}
        publicKey = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq/Tb1W3wyaNPF5sRO+IERXjWkSP0VYdg+FTmoNA9LaSnH1aOETgitX5Nm4BjUgcrAztk5Xxc88HRjTMTRxgVEs8/E65Tk6IfAwQ/IdbUAIuFrbfzapEPnZFJ+ta5+2gUQ7JuFMFgPwxGaQyzO4FXSYPkhKKtzc+y7h90JcRzQ6LkKP7vus/OSkbm/Dz9ekyRqStqiy556xM6UV4+ylDl+vK+ITVj5MXbXSt/R3elUVRZ8Z/2w9CEGXmerbCtCvB7zQDDzNx94StO7v8cPTq4vazLS7WKOJ5e1EA1zBWEfMf4t2LpMNT/uwr3T7fRS7VTTcr5LQyhFeK2lTAEd8059QIDAQAB"
        issuer = "http://0.0.0.0:8080/"
        audience = "http://0.0.0.0:8080/"
        realm = "Luurk"
    }
}
