

ktor {
    deployment {
        port = 8080,
        host = "0.0.0.0"
    }
    application {
        modules = [ com.example.luurk.ApplicationKt.module ]
    }
    database {
        url = "r2dbc:postgresql://localhost:5433/postgres"
        driver = "postgresql"
        user = "luurk-user"
        password = ${?DB_PASSWORD}
    }
    jwt {
        privateKey = ${?JWT_PK}
        issuer = "luurk-api"
        audience = "luurk-api"
        realm = "Luurk"
    }
}
